// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NSSFLIPobj.InfrastructureServices.Gateways.Database;

namespace NonStationaryShoppingFacilitiesLocatedInParks.WebService.Migrations
{
    [DbContext(typeof(NSSFLIPobjContext))]
    [Migration("20200601053742_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("NSSFLIPobj.DomainObjects.NSSFLIPobj", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adress")
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaObj")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodAdrIP")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractFinishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroundsForConcluding")
                        .HasColumnType("TEXT");

                    b.Property<string>("KindObj")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameObj")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOfBusinessEntity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberOfContract")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlacementPeriod")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialization")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeOfContract")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NSSFLIPobjs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AdminArea = "Восточный административный округ",
                            Adress = "город Москва, улица Сокольнический Вал, дом 1, строение 1",
                            AreaObj = "285",
                            CodAdrIP = "2109201",
                            ContractFinishDate = "30.06.2020",
                            ContractStartDate = "30.06.2015",
                            ContractStatus = "действует",
                            District = "Район Сокольники",
                            GroundsForConcluding = "Результат аукциона (победитель)",
                            KindObj = "павильон",
                            NameObj = "№1, Нижний майский пруд между Майским просеком и Богородским шоссе",
                            NameOfBusinessEntity = "Ветров Михаил Владимирович",
                            Number = "1",
                            NumberOfContract = "592/15-A",
                            PlacementPeriod = "с 1 января по 31 декабря",
                            Specialization = "кафе",
                            TradingStartDate = "30.06.2015",
                            TypeOfContract = "договор на осущевствление торговой деятельности"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
